### PR TITLE
Increase RTP RECV BUFFER size

### PR DESCRIPTION
**Pull request by Unknownforce351**
Fixes some surround audio issues on RPi 1/2/3 on Gen5+ servers.

### CODE REVIEW

**Comment by cgutman** [comment]
I will take this PR, however I believe that Moonlight Embedded needs to disable direct-submit in the audio renderer before this change will net a positive impact. @irtimmer was using this smaller recv buffer to enforce a latency ceiling on the audio stream if it can't keep up with decoding (as it often can't on the Pi 1). With this change alone, it's likely to significantly increase the audio latency on Pi 1. Once the direct submit flag is removed, the latency will be capped at 30 samples (150 ms).

**Comment by Unknownforce351** [comment]
Ahh, that explains why it's set that way, but I would think that this should match up to what's being sent from the host.  Assuming I'm understanding exactly how this works.  But I probably don't, I'm only a simple amateur. :)

Just thinking out loud on this one, but shouldn't that be listed as a limitation for the Pi 1 and/or set as a .patch to compile for the Pi 1 if that is the case?  Going forward, I would think that Pi 1 will be "phased out" as the Pi 2 and 3 are far superior devices for the same price, not to mention, Embedded and Pi 1 aren't the only app and hardware using moonlight-common-c.  Although, I suppose Embedded is probably the most commonly used app using it at this point.

I guess I'm good either way, since I can always just make the simple change when updating, so maybe we should just wait until he wants/chooses to remove the flag.

Anyway, my opinion probably doesn't merit much value anyway, just figured I'd offer my 2 cents. ;)

Thanks!

**Comment by cgutman** [comment]
The host buffer size doesn't really matter. The receive buffer is just meant to give the application and kernel enough time to read packets out of the buffer. The problem is that direct submit means that we'll be doing Opus decoding on the receive thread which is a bad idea for low power platforms like Embedded runs on, and even worse when we're decoding 6 channels of Opus instead of 2.

Now that I'm thinking more about it, can you remove the CAPABILITY_DIRECT_SUBMIT flag from the audio renderers and see if that fixes your issue without requiring this buffer size change?

**Comment by Unknownforce351** [comment]
I'll give it a shot when I get a chance.

**Comment by Unknownforce351** [comment]
Setting capabilities to 0 (which I am assuming is the proper way to do that) resolved my problems. So I am guessing this fix is unnecessary Then.

**Comment by cgutman** [comment]
I'm going to take this change because it eliminates this difference between C and Java moonlight-common implementations. But please make sure the appropriate changes are made in Moonlight Embedded or this may cause latency problems. File an issue or PR to get the audio capabilities set to 0 on at least Pi 1.

**Pull request merged**
