### PR TITLE
vita: Apply newlib changes

### PR DESCRIPTION
**Pull request by d3m3vilurr**
no more need to define `TCP_NODELAY` and `sockaddr_in6` parts

### CODE REVIEW

**Comment by d3m3vilurr** [comment]
i'll check both of enet and common-c

**Comment by d3m3vilurr** [comment]
done :)

**Comment by cgutman** [comment]
Thanks! This will make maintaining the IPv6 code in moonlight-common-c much easier :)

**Comment by d3m3vilurr** [comment]
hehe.. sorry i didnt have free time. and this patch needs to update enet :)

**Pull request merged**
