### PR TITLE
CMakeLists.txt tweaks

### PR DESCRIPTION
**Pull request by mariotaku**
Sorry for making this rather big change. Hopefully it can keep compatibility for other projects.

 - Allows static library compilation, by explicitly set `BUILD_SHARED_LIBS` to false.
 - Links to MBedTLS/OpenSSL based on build option
 - ~~Allows `-Werror` option to be turned off~~ (Removed as strict aliasing warnings are fixed)
 - Limits visibility of some defines and headers

### CODE REVIEW

**Comment by mariotaku** [comment]
Recent change introduced a build script from cURL project. Not sure if it's OK, but if not, I'll write one, and squash previous commits.

**Comment by cgutman** [comment]
Let's use our own to avoid any licensing or copyright concerns.

**Comment by mariotaku** [comment]
Done. I have changed to own implementation. Although some lines are the similar to others' but I think can't be avoided.

**Comment by cgutman** [comment]
It looks like there's a CMake warning generated in the MbedTLS builds:
```
CMake Warning (dev) at /usr/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:424 (message):
  The package name passed to `find_package_handle_standard_args` (MBEDTLS)
  does not match the name of the calling package (MbedTLS).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/FindMbedTLS.cmake:16 (find_package_handle_standard_args)
  CMakeLists.txt:38 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

Can you fix that?

**Comment by mariotaku** [comment]
Done :)

**Comment by cgutman** [comment]
Squashed and merged as 179970a0d5ed4baee76bd72a2a4a16b3cecb0da5

**Pull request closed without merging**
